package py.com.ventu.app.ventas;

import java.awt.event.KeyEvent;
import static java.awt.event.KeyEvent.VK_ENTER;
import java.awt.event.KeyListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import py.com.ventu.controladores.ConfiguracionesJpaController;
//import py.com.ventu.controladores.ExistenciaSucursalJpaController;
import py.com.ventu.controladores.FacturaVentaDetJpaController;
import py.com.ventu.controladores.FacturaVentaJpaController;
import py.com.ventu.entidades.Configuraciones;
//import py.com.ventu.entidades.ExistenciaStock;
//import py.com.ventu.entidades.ExistenciaStockPK;
import py.com.ventu.entidades.FacturaVenta;
import py.com.ventu.entidades.FacturaVentaDet;
import py.com.ventu.entidades.Usuario;
import py.com.ventu.util.NumeroToLetras;

/**
 * @author cpatino
 */
public class FrmComprobantesEmitidos extends javax.swing.JInternalFrame {

    private EntityManager em;

    private Usuario usuario;
    private FacturaVenta facturaVenta;
    private Configuraciones conf;

    private FacturaVentaJpaController facturaVentaService;
    private FacturaVentaDetJpaController facturaVentaDetService;
//    private ExistenciaSucursalJpaController existenciaService;
    private ConfiguracionesJpaController configuracionesService;

    private Logger log;

    private DefaultTableModel modelProductos;

    private String formulario;
    private String tipoMovimiento;

    private Integer cantVentas;
    private Integer posLista;

    private List<FacturaVenta> listaVentas;
    private List<FacturaVentaDet> listaVentasDet;

    /**
     * Creates new form FrmGestionComprobantes
     */
    public FrmComprobantesEmitidos() {
        initComponents();
    }

    public FrmComprobantesEmitidos(EntityManager ema, Usuario user, Logger logger) {
        initComponents();

        this.em = ema;
        this.usuario = user;
        this.log = logger;

        iniciarComponentes(); // en caso que se instancien con diferentes parametros
    }

    public void iniciarComponentes() {
        facturaVentaService = new FacturaVentaJpaController(em);
        facturaVentaDetService = new FacturaVentaDetJpaController(em);
//        existenciaService = new ExistenciaSucursalJpaController(em);
        configuracionesService = new ConfiguracionesJpaController(em);

        keyListener();
        inicializarValores();
        tableModelProductos();
        cargarListaRegistros(0);
        desplegarPrimerRegistro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        radTicket = new javax.swing.JRadioButton();
        radFactura = new javax.swing.JRadioButton();
        txtComprobante = new javax.swing.JTextField();
        lblTipoMovimiento = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNroInterno = new javax.swing.JLabel();
        lblComprobante = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cmdAnterior = new javax.swing.JButton();
        cmdPrimero = new javax.swing.JButton();
        cmdSiguiente = new javax.swing.JButton();
        cmdUltimo = new javax.swing.JButton();
        txtFecha = new com.toedter.calendar.JDateChooser();
        lblEstadoComprobante = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblFactura = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabProductos = new javax.swing.JTable();
        panels1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblFechaVenta = new javax.swing.JLabel();
        lblTipoVenta = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        asdfa = new javax.swing.JLabel();
        lblGrupoCliente = new javax.swing.JLabel();
        lblVendedor = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        cmdSalir = new javax.swing.JButton();
        cmdReimprimirFactura = new javax.swing.JButton();
        cmdReimprimirTicket = new javax.swing.JButton();
        cmdAnular = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtTotalVenta = new javax.swing.JFormattedTextField();
        lblMotivo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Comprobantes Emitidos");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel1.setText("Tipo de Movimiento");

        buttonGroup1.add(radTicket);
        radTicket.setText("Nro. de Ticket");
        radTicket.setToolTipText("Filtrar comprobante por ticket");
        radTicket.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radTicketStateChanged(evt);
            }
        });
        radTicket.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radTicketItemStateChanged(evt);
            }
        });

        buttonGroup1.add(radFactura);
        radFactura.setText("Nro. de Factura");
        radFactura.setToolTipText("Filtrar comprobante por factura");
        radFactura.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radFacturaStateChanged(evt);
            }
        });

        txtComprobante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtComprobanteKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtComprobanteKeyPressed(evt);
            }
        });

        lblTipoMovimiento.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblTipoMovimiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipoMovimiento.setText("lblTipoMovimiento");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ticket");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nro. Interno");

        lblNroInterno.setFont(new java.awt.Font("DejaVu Sans", 1, 15)); // NOI18N
        lblNroInterno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNroInterno.setText("lblNroInterno");

        lblComprobante.setFont(new java.awt.Font("DejaVu Sans", 1, 15)); // NOI18N
        lblComprobante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComprobante.setText("lblComprobante");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cmdAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/py/com/progress/sgf/imagenes/anterior_16.png"))); // NOI18N
        cmdAnterior.setToolTipText("Registro anterior");
        cmdAnterior.setPreferredSize(new java.awt.Dimension(30, 30));
        cmdAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAnteriorActionPerformed(evt);
            }
        });

        cmdPrimero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/py/com/progress/sgf/imagenes/primero_16.png"))); // NOI18N
        cmdPrimero.setToolTipText("Primer registro");
        cmdPrimero.setPreferredSize(new java.awt.Dimension(30, 30));
        cmdPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPrimeroActionPerformed(evt);
            }
        });

        cmdSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/py/com/progress/sgf/imagenes/siguiente_16.png"))); // NOI18N
        cmdSiguiente.setToolTipText("Registro siguiente");
        cmdSiguiente.setPreferredSize(new java.awt.Dimension(30, 30));
        cmdSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSiguienteActionPerformed(evt);
            }
        });

        cmdUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/py/com/progress/sgf/imagenes/ultimo_16.png"))); // NOI18N
        cmdUltimo.setToolTipText("Último registro");
        cmdUltimo.setPreferredSize(new java.awt.Dimension(30, 30));
        cmdUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdUltimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(cmdPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmdAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(cmdSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(cmdUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(cmdPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        txtFecha.setToolTipText("Filtrar por fecha");
        txtFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFechaKeyPressed(evt);
            }
        });

        lblEstadoComprobante.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        lblEstadoComprobante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstadoComprobante.setText("Anulado");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Factura");

        lblFactura.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        lblFactura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFactura.setText("001-001-1234567");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(radFactura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radTicket, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTipoMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNroInterno, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblEstadoComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTipoMovimiento)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radTicket)
                    .addComponent(txtComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNroInterno)
                    .addComponent(lblComprobante)
                    .addComponent(lblFactura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radFactura)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblEstadoComprobante, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        tabProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Producto", "Cant", "Precio", "Dto. %", "Dscto.", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabProductos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabProductos.setRowHeight(22);
        tabProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabProductosMouseClicked(evt);
            }
        });
        tabProductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabProductosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabProductos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panels1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Cliente:");

        jLabel5.setText("Fecha:");

        jLabel6.setText("Tipo de Venta:");

        lblCliente.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblCliente.setText("jLabel7");

        lblFechaVenta.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblFechaVenta.setText("jLabel8");

        lblTipoVenta.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblTipoVenta.setText("jLabel9");

        jLabel10.setText("Grupo:");

        asdfa.setText("Vendedor:");

        lblGrupoCliente.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblGrupoCliente.setText("jLabel11");

        lblVendedor.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblVendedor.setText("jLabel12");

        javax.swing.GroupLayout panels1Layout = new javax.swing.GroupLayout(panels1);
        panels1.setLayout(panels1Layout);
        panels1Layout.setHorizontalGroup(
            panels1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panels1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panels1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panels1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTipoVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panels1Layout.createSequentialGroup()
                        .addGroup(panels1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panels1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panels1Layout.createSequentialGroup()
                                .addComponent(lblFechaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panels1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panels1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblGrupoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(panels1Layout.createSequentialGroup()
                                        .addComponent(asdfa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20))
                            .addGroup(panels1Layout.createSequentialGroup()
                                .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        panels1Layout.setVerticalGroup(
            panels1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panels1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panels1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panels1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblFechaVenta)
                    .addComponent(jLabel10)
                    .addComponent(lblGrupoCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panels1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblTipoVenta)
                    .addComponent(asdfa)
                    .addComponent(lblVendedor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cmdSalir.setText("Salir");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });

        cmdReimprimirFactura.setText("Reimprimir Factura");
        cmdReimprimirFactura.setPreferredSize(new java.awt.Dimension(39, 29));
        cmdReimprimirFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdReimprimirFacturaActionPerformed(evt);
            }
        });

        cmdReimprimirTicket.setText("Reimprimir Ticket");
        cmdReimprimirTicket.setPreferredSize(new java.awt.Dimension(39, 29));
        cmdReimprimirTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdReimprimirTicketActionPerformed(evt);
            }
        });

        cmdAnular.setText("Anular Venta");
        cmdAnular.setPreferredSize(new java.awt.Dimension(39, 29));
        cmdAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAnularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdReimprimirFactura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(cmdReimprimirTicket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdAnular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmdAnular, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdReimprimirTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdReimprimirFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Total Venta:");

        txtTotalVenta.setEditable(false);
        txtTotalVenta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtTotalVenta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalVenta.setToolTipText("Importe Total de la venta");
        txtTotalVenta.setFocusable(false);
        txtTotalVenta.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMotivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotalVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblMotivo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panels1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panels1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSiguienteActionPerformed
        if (posLista < cantVentas - 1) {
            facturaVenta = listaVentas.get(posLista + 1);
            cargarCampos();
            posLista++;
        }
    }//GEN-LAST:event_cmdSiguienteActionPerformed

    private void tabProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabProductosMouseClicked

    }//GEN-LAST:event_tabProductosMouseClicked

    private void tabProductosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabProductosKeyPressed
        procesarKeyEvent(evt);
    }//GEN-LAST:event_tabProductosKeyPressed

    private void radTicketItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radTicketItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_radTicketItemStateChanged

    private void radTicketStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radTicketStateChanged
        cambiarMovimiento();
    }//GEN-LAST:event_radTicketStateChanged

    private void radFacturaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radFacturaStateChanged
        cambiarMovimiento();
    }//GEN-LAST:event_radFacturaStateChanged

    private void cmdPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrimeroActionPerformed
        if (cantVentas > 0) {
            facturaVenta = listaVentas.get(0);
            cargarCampos();
            posLista = 0;
        }
    }//GEN-LAST:event_cmdPrimeroActionPerformed

    private void cmdAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAnteriorActionPerformed
        if (posLista > 0) {
            facturaVenta = listaVentas.get(posLista - 1);
            cargarCampos();
            posLista--;
        }
    }//GEN-LAST:event_cmdAnteriorActionPerformed

    private void cmdUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUltimoActionPerformed
        if (cantVentas > 0) {
            facturaVenta = listaVentas.get(cantVentas - 1);
            cargarCampos();
            posLista = cantVentas - 1;
        }
    }//GEN-LAST:event_cmdUltimoActionPerformed

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_cmdSalirActionPerformed

    private void txtComprobanteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComprobanteKeyPressed
        if (evt.getKeyCode() == VK_ENTER) {
            buscarComprobante();
        } else {
            procesarKeyEvent(evt);
        }
    }//GEN-LAST:event_txtComprobanteKeyPressed

    private void txtComprobanteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComprobanteKeyTyped
        char car = evt.getKeyChar();
        if (car == '-' || (car >= '0' && car <= '9')) {
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_txtComprobanteKeyTyped

    private void txtFechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyPressed
        if (evt.getKeyCode() == VK_ENTER && this.txtFecha.getDate() != null) {
            buscarComprobanteFecha();
        }
        procesarKeyEvent(evt);
    }//GEN-LAST:event_txtFechaKeyPressed

    private void cmdReimprimirTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdReimprimirTicketActionPerformed
        imprimir(1);
    }//GEN-LAST:event_cmdReimprimirTicketActionPerformed

    private void cmdReimprimirFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdReimprimirFacturaActionPerformed
       /* if (facturaVenta.getNroDocum() == 0) {
            JOptionPane.showMessageDialog(null, "La venta seleccionada no posee factura de venta. Utilice Reimprimir Ticket.",
                    formulario, JOptionPane.ERROR_MESSAGE);
        } else {
            imprimir(2);
        }*/
    }//GEN-LAST:event_cmdReimprimirFacturaActionPerformed

    private void cmdAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAnularActionPerformed
        if (facturaVenta.getEstado() == 3) {
            JOptionPane.showMessageDialog(null, "La venta seleccionada ya fue anulada.",
                    formulario, JOptionPane.INFORMATION_MESSAGE);
        } else {
            int showConfirmDialog = JOptionPane.showConfirmDialog(null,
                    "Está seguro que desea anular esta venta.",
                    "Anular Venta", JOptionPane.YES_NO_OPTION);
            if (showConfirmDialog == 0) {
                anularVenta();
                showConfirmDialog = JOptionPane.showConfirmDialog(null,
                        "Realizar reingreso al stock de los productos de la venta anulada?",
                        "Anular Venta", JOptionPane.YES_NO_OPTION);
                if (showConfirmDialog == 0) {
                    reingresarStock();
                }
            }
            
            actualizarListaRegistros();
        }
    }//GEN-LAST:event_cmdAnularActionPerformed

    public void keyListener() {
        KeyListener listener = new KeyListener() {

            @Override
            public void keyTyped(KeyEvent e) {
            }

            @Override
            public void keyPressed(KeyEvent e) {
                procesarKeyEvent(e);
            }

            @Override
            public void keyReleased(KeyEvent e) {
            }
        };
        addKeyListener(listener);
        setFocusable(true);
    }

    public void procesarKeyEvent(KeyEvent evt) {
        // no hay nada que implementar
    }

    private void inicializarValores() {
        this.lblMotivo.setText("");
        this.lblTipoMovimiento.setText("Nro. de Ticket");
        this.tipoMovimiento = "ticket";
        this.lblCliente.setText("");
        this.lblGrupoCliente.setText("");
        this.lblFechaVenta.setText("");
        this.lblTipoVenta.setText("");
        this.lblVendedor.setText("");
        this.txtTotalVenta.setValue(0);
        this.lblEstadoComprobante.setText("");
        this.lblFactura.setText("");

        this.radTicket.setSelected(true);

        this.posLista = 0;

        this.formulario = "Comprobantes Emitidos";
        this.facturaVenta = new FacturaVenta();
        this.conf = configuracionesService.buscarConfiguraciones(1);
    }

    public void tableModelProductos() {
        modelProductos = (DefaultTableModel) this.tabProductos.getModel();
        modelProductos.setNumRows(0);

        tabProductos.getColumnModel().getColumn(1).setPreferredWidth(230);
        tabProductos.getColumnModel().getColumn(2).setPreferredWidth(60);
        tabProductos.getColumnModel().getColumn(4).setPreferredWidth(60);
    }

    public void cambiarMovimiento() {
        if (radFactura.isSelected()) {
            this.lblTipoMovimiento.setText("Nro. de Factura");
            this.tipoMovimiento = "factura";
        } else {
            this.lblTipoMovimiento.setText("Nro. de Ticket");
            this.tipoMovimiento = "ticket";
        }
    }

    public void cargarListaRegistros(int busco) {
        listaVentas = facturaVentaService.listarVentas();
        cantVentas = listaVentas.size();

        if (listaVentas.size() > 0) {
            posLista = busco;

            facturaVenta = listaVentas.get(posLista);
            cargarCampos();
        }
    }

    public void actualizarListaRegistros() {
        listaVentas = facturaVentaService.listarVentas();
        cargarListaRegistros(posLista);
    }

    private void desplegarPrimerRegistro() {
        if (listaVentas.size() > 0) {
            posLista = 0;
            facturaVenta = listaVentas.get(posLista);
            cargarCampos();
        }
    }

    public void cargarCampos() {
        try {
//            this.lblNroInterno.setText(String.valueOf(facturaVenta.getNroTrans()));
            this.lblComprobante.setText(String.valueOf(facturaVenta.getTicket()));
           // this.lblMotivo.setText(facturaVenta.getObservacion());

            /*this.lblCliente.setText(facturaVenta.getCliente().getId() + "  " + facturaVenta.getCliente().getCliente());
            this.lblGrupoCliente.setText(facturaVenta.getCliente().getGrupoCliente().getDescripcion());
            this.lblFechaVenta.setText(new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(facturaVenta.getFecha()));
            this.lblVendedor.setText(facturaVenta.getVendedor().getNombre());
            this.txtTotalVenta.setValue(facturaVenta.getTotal());
*/
            if (facturaVenta.getCondicionVenta() == 1) {
                this.lblTipoVenta.setText("1 Venta Contado");
            }
            if (facturaVenta.getCondicionVenta() == 2) {
                this.lblTipoVenta.setText("2 Venta Crédito");
            } else {
                this.lblTipoVenta.setText("3 Venta Tarjeta");
            }

            if (facturaVenta.getEstado() == 2) {
                this.lblEstadoComprobante.setText("PENDIENTE");
            }
            if (facturaVenta.getCondicionVenta() == 3) {
                this.lblEstadoComprobante.setText("ANULADO");
            } else {
                this.lblEstadoComprobante.setText("");
            }

            /*if (facturaVenta.getNroDocum() > 0) {
                this.lblFactura.setText(facturaVenta.getCodEmiFac() + "-"
                        + facturaVenta.getCodSucFac() + "-" + String.valueOf(facturaVenta.getNroDocum()));
            } else {
                this.lblFactura.setText("");
            }*/

            cargarDetalleVenta();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void cargarDetalleVenta() {
     List<FacturaVentaDet> listaDetalle = facturaVentaDetService.buscarListaDetalleVenta(facturaVenta.getTicket());
        listaVentasDet = listaDetalle;
        tableModelProductos();
        try {
            for (FacturaVentaDet fvd : listaDetalle) {
                modelProductos.addRow(new Object[]{
                    fvd.getProducto().getCodigo(),
                    //fvd.getProducto().getDescripcion() + " " + fvd.getProducto().getPresentacion(),
                    fvd.getCantidad(),
                    fvd.getPrecioUnit(),
                    fvd.getProcDscto(),
                    fvd.getImpDscto(),
                    fvd.getSubototal()
                });
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error al cargar detalle de la venta."
                    + "\n" + ex.getMessage(), formulario, JOptionPane.ERROR_MESSAGE);
            log.info(formulario + "; Proceso: CargarDetalleVenta ; " + ex.getMessage() + " ; CAUSA: " + ex.getCause());
            ex.printStackTrace();
        }
    }

    public void buscarComprobante() {
        FacturaVenta ven = new FacturaVenta();
        int cant = listaVentas.size();

        if (cant > 0) {
            try {
                Integer param = Integer.parseInt(this.txtComprobante.getText().trim());

                if (radTicket.isSelected()) {
                    for (int i = 0; i < cant; i++) {
                        ven = listaVentas.get(i);
                        if (ven.getTicket() == param) {
                            posLista = i;
                            facturaVenta = ven;
                            cargarCampos();
                            break;
                        }
                    }
                } else {
                    for (int i = 0; i < cant; i++) {
                        ven = listaVentas.get(i);
                        /*if (ven.getNroDocum() == param) {
                            posLista = i;
                            facturaVenta = ven;
                            cargarCampos()
                            break;
                        }*/
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    public void buscarComprobanteFecha() {
        FacturaVenta ven = new FacturaVenta();
        int cant = listaVentas.size();

        try {

            for (int i = 0; i < cant; i++) {
                ven = listaVentas.get(i);
                /*if (ven.getFecha().equals(this.txtFecha.getDate())) {
                    posLista = i;
                    facturaVenta = ven;
                    cargarCampos();
                    break;
                }*/
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void anularVenta() {
        try {

            String motivo = JOptionPane.showInputDialog(this, "Ingrese el motivo de la anulación de la venta.");

            facturaVenta.setEstado(3);
            //facturaVenta.setObservacion(motivo);

            facturaVentaService.editar(facturaVenta);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void reingresarStock() {
        try {
//            ExistenciaStockPK espk = new ExistenciaStockPK();
            //ExistenciaStock es = new ExistenciaStock();

            for (FacturaVentaDet fvd : listaVentasDet) {

                Double stockActual = 0.0;

               // espk.setProducto(fvd.getProducto().getCodigo());
               // espk.setSucursal(conf.getSucursal().getId());

//                es = existenciaService.findExistenciaSucursal(espk);

                //stockActual = es.getStockActual();
                //es.setStockActual(stockActual + fvd.getCantidad());

                //existenciaService.editar(es);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error realizar reingreso al stock de los productos de la venta."
                    + "\n" + e.getMessage(), formulario, JOptionPane.ERROR_MESSAGE);
            log.info(formulario + "; Proceso: ReingresoStock ; " + e.getMessage() + " ; CAUSA: " + e.getCause());
            e.printStackTrace();
        }
    }

    public void imprimir(int tipo) {
        try {
            Connection conexion;
            conexion = DriverManager.getConnection("jdbc:postgresql://localhost:5432/sgf", "postgres", "postgres");

            String reporte = "";

            // retorna el valor del importe en letras
            NumeroToLetras imp = new NumeroToLetras();
            String letras;// = imp.Convertir(this.facturaVenta.getTotal().toString(), true, 1);

            Map parametros = new HashMap();

            //parametros que enviamos al report.
            if (tipo == 1) {
                reporte = "py/com/progress/sgf/reportes/TicketVenta.jasper";
                parametros.put("nroTrans", facturaVenta.getTicket());
            } else {
                reporte = "py/com/progress/sgf/reportes/FacturaVenta.jasper";
                parametros.put("nroTrans", facturaVenta.getTicket());
                //parametros.put("monto_letras", letras);
            }

            JasperReport elReporte = (JasperReport) JRLoader.loadObject(ClassLoader.getSystemResource(reporte));
            JasperPrint imprimir = JasperFillManager.fillReport(elReporte, parametros, conexion);
            JasperViewer visor = new JasperViewer(imprimir, false);
            visor.setTitle("Ventas");
            visor.setVisible(true);
            conexion.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error al imprimir comprobante de venta "
                    + "\n" + ex.getMessage() + "\n" + ex.getCause(),
                    "Ventas", JOptionPane.ERROR_MESSAGE);
            log.info(formulario + "; Proceso: ImprimirComprobante ; " + ex.getMessage() + " ; CAUSA: " + ex.getCause());
            ex.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asdfa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cmdAnterior;
    private javax.swing.JButton cmdAnular;
    private javax.swing.JButton cmdPrimero;
    private javax.swing.JButton cmdReimprimirFactura;
    private javax.swing.JButton cmdReimprimirTicket;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JButton cmdSiguiente;
    private javax.swing.JButton cmdUltimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblComprobante;
    private javax.swing.JLabel lblEstadoComprobante;
    private javax.swing.JLabel lblFactura;
    private javax.swing.JLabel lblFechaVenta;
    private javax.swing.JLabel lblGrupoCliente;
    private javax.swing.JLabel lblMotivo;
    private javax.swing.JLabel lblNroInterno;
    private javax.swing.JLabel lblTipoMovimiento;
    private javax.swing.JLabel lblTipoVenta;
    private javax.swing.JLabel lblVendedor;
    private javax.swing.JPanel panels1;
    private javax.swing.JRadioButton radFactura;
    private javax.swing.JRadioButton radTicket;
    private javax.swing.JTable tabProductos;
    private javax.swing.JTextField txtComprobante;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JFormattedTextField txtTotalVenta;
    // End of variables declaration//GEN-END:variables
}
